---
- name: Unlock encrypted drives
  become: true
  ansible.builtin.systemd:
    state: started
    name: "systemd-cryptsetup@{{ item.name | default(item.uuid) }}"
  with_items: "{{ mounts_encrypted }}"

- name: Mount drives
  become: true
  args:
    warn: false
  ansible.builtin.command: mount -a
